# Generated by Django 5.0 on 2024-01-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptt_test', '0004_chapter_delete_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
